# Generated by Django 5.0.1 on 2024-02-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalInterviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=100, null=True)),
                ('resumeId', models.CharField(max_length=100, null=True)),
                ('strength', models.CharField(max_length=150, null=True)),
                ('weakness', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('overall_comments', models.CharField(max_length=280, null=True)),
                ('overall_rating', models.FloatField(null=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('proficiency', models.CharField(max_length=100, null=True)),
                ('ratingoutof10', models.PositiveIntegerField(null=True)),
                ('comments', models.CharField(max_length=150, null=True)),
                ('techReview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technicalLevel.technicalinterviewtable')),
            ],
        ),
    ]
