# Generated by Django 5.0.1 on 2024-02-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='candidate_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeId', models.CharField(max_length=255, unique=True)),
                ('appliedDate', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('assigned', models.CharField(max_length=50, null=True)),
                ('assignedDate', models.DateField(null=True)),
                ('interviewer', models.CharField(max_length=50, null=True)),
                ('interviewerAssignedDate', models.DateField(null=True)),
                ('currentStatus', models.CharField(default='NOT_ASSIGNED', max_length=50, null=True)),
                ('shortlistStatus', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=75, null=True)),
                ('resumeScore', models.CharField(max_length=255)),
                ('jobRole', models.CharField(max_length=75, null=True)),
                ('yearsOfExperience', models.CharField(max_length=255)),
                ('phoneNo', models.CharField(max_length=100, null=True)),
                ('yearOfGraduation', models.CharField(max_length=75, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('domainExperience', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('travelConstraint', models.CharField(max_length=100, null=True)),
                ('referenceName', models.CharField(max_length=50, null=True)),
                ('referenceEmail', models.EmailField(max_length=254, null=True, unique=True)),
                ('notificationPeriod', models.CharField(max_length=50, null=True)),
                ('fatherOccupation', models.CharField(max_length=50, null=True)),
                ('motherOccupation', models.CharField(max_length=50, null=True)),
                ('siblings', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('submissionStatus', models.CharField(max_length=20, null=True)),
                ('sourceMode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRLevel.sourcemode')),
            ],
        ),
        migrations.CreateModel(
            name='evaluationdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeId', models.CharField(max_length=255, unique=True)),
                ('longTermAssocaition', models.CharField(max_length=500, null=True)),
                ('joinDate', models.DateField()),
                ('specialRequest', models.CharField(max_length=100, null=True)),
                ('hrFeedback', models.CharField(max_length=1000, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('hrStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRLevel.status')),
            ],
        ),
    ]
