# Generated by Django 5.0.1 on 2024-02-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationdata',
            name='hrStatus',
        ),
        migrations.AddField(
            model_name='evaluationdata',
            name='shortlistStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evaluationdata',
            name='submissionStatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
