# Generated by Django 5.0.1 on 2024-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0002_remove_evaluationdata_hrstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate_info',
            old_name='submissionStatus',
            new_name='interviewerSubmissionStatus',
        ),
        migrations.AddField(
            model_name='candidate_info',
            name='recruiterSubmissionStatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
