# Generated by Django 5.0.1 on 2024-02-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0003_rename_submissionstatus_candidate_info_interviewersubmissionstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_info',
            name='resume_Link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
