# Generated by Django 5.0.3 on 2024-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0004_candidate_info_resume_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=20, null=True)),
                ('filename', models.CharField(max_length=200, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='meetingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingURL', models.TextField()),
                ('candidate', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
