# Generated by Django 5.0.3 on 2024-03-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0005_attachments_meetingdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attachments',
        ),
    ]
