# Generated by Django 5.0.3 on 2024-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0006_delete_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate_info',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='candidate_info',
            name='interviewer',
            field=models.ManyToManyField(null=True, to='HRLevel.interviewer'),
        ),
    ]
