# Generated by Django 5.0.3 on 2024-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLevel', '0007_interviewer_remove_candidate_info_interviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_info',
            name='interviewer',
        ),
        migrations.DeleteModel(
            name='interviewer',
        ),
        migrations.AddField(
            model_name='candidate_info',
            name='interviewer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
